language: go
go:
    - 1.7
sudo: required
before_install:
    - sudo add-apt-repository -y ppa:masterminds/glide
    - sudo apt-get -qq update
    - sudo apt-get -y install glide
install:
    - glide up
